# Generated by Django 3.2.14 on 2022-07-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_username_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mode'),
        ),
    ]
